# System commands
EXIT = ".EXIT"

# Database commands
CREATE_DATABASE = "DATABASE"
DELETE_DATABASE = "DROP DATABASE "
USE_DATABASE = "USE"

# Table Commands
CREATE_TABLE = "TABLE "
DROP_TABLE = "DROP TABLE "
ALTER_TABLE = "ALTER TABLE "
SELECT = "SELECT "
