# Authors: Amir Behmaram and Tanner Jones
# Date: 5/8/2018
# Version: 4.0

# Global variables to be used in databse file
CREATE = "create"
USE = "use"
DATABASE = "database"
TABLE = "table"
ALTER = "alter"
ADD = "add"
DROP = "drop"
COLUMN = "column"
SELECT = "select"
FROM = "from"
INSERT = "insert"
INTO = "into"
VALUES = "values"
STAR = "*"
EQUAL = "="
NOT_EQUAL = "!="
GREATER = ">"
LESS = "<"
GREATER_EQUAL = ">="
LESS_EQUAL = "<="
INNER = "inner"
JOIN = "join"
LEFT = "left"
OUTER = "outer"
UPDATE = "update"
SET = "set"
WHERE = "where"
